import { describe, expect, it } from "vitest";
import { buildEdi837P } from "./x837p";
import { buildEdi835, parseEdi835 } from "./x835";

describe("837P generator", () => {
  it("produces a well-formed interchange with claim and service lines", () => {
    const edi = buildEdi837P({
      controlNumber: "CMD000001",
      interchangeControl: "123456789",
      senderId: "COLLABORATMD",
      receiverId: "00590",
      now: new Date("2026-09-21T14:30:00Z"),
      billingProvider: { name: "Lakeside Family Medicine", npi: "1234567893", taxId: "12-3456789", address1: "410 Lakeside Ave", city: "Orlando", state: "FL", zip: "32801" },
      renderingProvider: { lastName: "Chen", firstName: "Sarah", npi: "1234567893", taxonomy: "207Q00000X" },
      payer: { name: "BCBS FL", payerId: "00590" },
      subscriber: { lastName: "Garcia", firstName: "Maria", memberId: "ABC123", groupNumber: "GRP1", dob: "1980-04-12", sex: "F", address1: "1 Main St", city: "Orlando", state: "FL", zip: "32801", relationship: "self" },
      claim: { totalCents: 21000, placeOfService: "11", frequencyCode: "1", dateOfService: "2026-09-01", diagnoses: ["E11.9", "I10"] },
      lines: [
        { cpt: "99214", modifiers: ["25"], chargeCents: 19500, units: 1, dxPointers: [1, 2], dateOfService: "2026-09-01" },
        { cpt: "36415", modifiers: [], chargeCents: 1500, units: 1, dxPointers: [1], dateOfService: "2026-09-01" },
      ],
    });
    const segs = edi.split("~").map((s) => s.trim()).filter(Boolean);
    expect(segs[0].startsWith("ISA*00*")).toBe(true);
    expect(edi).toContain("ST*837*0001*005010X222A1");
    expect(edi).toContain("CLM*CMD000001*210.00***11:B:1*Y*A*Y*Y");
    expect(edi).toContain("HI*ABK:E119*ABF:I10");
    expect(edi).toContain("SV1*HC:99214:25*195.00*UN*1***1:2");
    // NM105-NM107 (middle, prefix, suffix) are empty, so four separators precede the MI qualifier.
    expect(edi).toContain("NM1*IL*1*Garcia*Maria****MI*ABC123");
    expect(edi).toContain("DMG*D8*19800412*F");
    expect(edi).toContain("NM1*PR*2*BCBS FL*****PI*00590");
    const se = segs.find((s) => s.startsWith("SE*"))!.split("*");
    const stIndex = segs.findIndex((s) => s.startsWith("ST*"));
    const seIndex = segs.findIndex((s) => s.startsWith("SE*"));
    expect(Number(se[1])).toBe(seIndex - stIndex + 1);
    expect(segs.at(-1)).toBe("IEA*1*123456789");
  });
});

describe("835 round trip", () => {
  it("parses payments, adjustments and remark codes generated by buildEdi835", () => {
    const raw = buildEdi835({
      payerName: "Aetna",
      payerId: "60054",
      checkNumber: "EFT12345",
      paymentDate: new Date("2026-09-20T00:00:00Z"),
      claims: [
        {
          patientControlNumber: "CMD000001",
          payerClaimNumber: "PCN1",
          statusCode: "1",
          chargedCents: 21000,
          paidCents: 14000,
          patientResponsibilityCents: 2500,
          adjustments: [],
          lines: [
            { cpt: "99214", chargedCents: 19500, paidCents: 13000, units: 1, adjustments: [{ group: "CO", reason: "45", amountCents: 4000 }, { group: "PR", reason: "3", amountCents: 2500 }] },
            { cpt: "36415", chargedCents: 1500, paidCents: 1000, units: 1, adjustments: [{ group: "CO", reason: "45", amountCents: 500 }] },
          ],
        },
        { patientControlNumber: "CMD000002", payerClaimNumber: "PCN2", statusCode: "4", chargedCents: 15000, paidCents: 0, patientResponsibilityCents: 0, adjustments: [{ group: "CO", reason: "197", amountCents: 15000 }], remarks: ["N54"], lines: [] },
      ],
    });
    const remit = parseEdi835(raw);
    expect(remit.payerName).toBe("Aetna");
    expect(remit.payerId).toBe("60054");
    expect(remit.checkNumber).toBe("EFT12345");
    expect(remit.paymentDate).toBe("2026-09-20");
    expect(remit.totalPaidCents).toBe(14000);
    expect(remit.claims).toHaveLength(2);
    const [paid, denied] = remit.claims;
    expect(paid.lines).toHaveLength(2);
    expect(paid.lines[0].adjustments).toEqual([
      { group: "CO", reason: "45", amountCents: 4000 },
      { group: "PR", reason: "3", amountCents: 2500 },
    ]);
    expect(denied.statusCode).toBe("4");
    expect(denied.adjustments[0]).toEqual({ group: "CO", reason: "197", amountCents: 15000 });
    expect(denied.remarks).toEqual(["N54"]);
  });
});
