/**
 * CMS place of service codes (the POS code set, as published by CMS for
 * professional claims): one list for charge entry, claim edits, locations and
 * the scrubber, so a code offered on a screen is one the scrubber accepts.
 */
export const PLACES_OF_SERVICE: [code: string, name: string][] = [
  ["11", "Office"],
  ["02", "Telehealth other than in patient's home"],
  ["10", "Telehealth in patient's home"],
  ["12", "Home"],
  ["01", "Pharmacy"],
  ["03", "School"],
  ["04", "Homeless shelter"],
  ["05", "Indian Health Service free-standing facility"],
  ["06", "Indian Health Service provider-based facility"],
  ["07", "Tribal 638 free-standing facility"],
  ["08", "Tribal 638 provider-based facility"],
  ["09", "Prison/correctional facility"],
  ["13", "Assisted living facility"],
  ["14", "Group home"],
  ["15", "Mobile unit"],
  ["16", "Temporary lodging"],
  ["17", "Walk-in retail health clinic"],
  ["18", "Place of employment/worksite"],
  ["19", "Off-campus outpatient hospital"],
  ["20", "Urgent care facility"],
  ["21", "Inpatient hospital"],
  ["22", "On-campus outpatient hospital"],
  ["23", "Emergency room, hospital"],
  ["24", "Ambulatory surgical center"],
  ["25", "Birthing center"],
  ["26", "Military treatment facility"],
  ["27", "Outreach site/street"],
  ["31", "Skilled nursing facility"],
  ["32", "Nursing facility"],
  ["33", "Custodial care facility"],
  ["34", "Hospice"],
  ["41", "Ambulance, land"],
  ["42", "Ambulance, air or water"],
  ["49", "Independent clinic"],
  ["50", "Federally qualified health center"],
  ["51", "Inpatient psychiatric facility"],
  ["52", "Psychiatric facility, partial hospitalization"],
  ["53", "Community mental health center"],
  ["54", "Intermediate care facility/individuals with intellectual disabilities"],
  ["55", "Residential substance abuse treatment facility"],
  ["56", "Psychiatric residential treatment center"],
  ["57", "Non-residential substance abuse treatment facility"],
  ["58", "Non-residential opioid treatment facility"],
  ["60", "Mass immunization center"],
  ["61", "Comprehensive inpatient rehabilitation facility"],
  ["62", "Comprehensive outpatient rehabilitation facility"],
  ["65", "End-stage renal disease treatment facility"],
  ["66", "Programs of All-Inclusive Care for the Elderly (PACE) center"],
  ["71", "Public health clinic"],
  ["72", "Rural health clinic"],
  ["81", "Independent laboratory"],
  ["99", "Other place of service"],
];

export const POS_CODES = new Set(PLACES_OF_SERVICE.map(([c]) => c));
export const posLabel = (code: string) => `${code} - ${PLACES_OF_SERVICE.find(([c]) => c === code)?.[1] ?? "Unknown"}`;
